### ISSUE TITLE
Change build.xml to use recommended Composer settings

### ISSUE THREAD

**Issue by silbinarywolf** [symbiote/silverstripe-base#21]
Need to update build.xml to the following.
When our CI systems are building, they should then use `ni_build` flags.
(ni_build does things like create the `silverstripe-cache` folder as well)

```
<property name="composer.dev" value="" />
<property name="composer.source" value="--prefer-source" />
<if>
	<isset property="composer_dist" />
	<then>
		<property name="composer.source" value="--prefer-dist" override="true" />
	</then>
</if>
<if>
	<!-- Non-Interactive Build, ie. For CI -->
	<isset property="ni_build" />
	<then>
		<property name="composer.source" value="--prefer-dist --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile" override="true" />
	</then>
</if>
```

**Comment by nglasl** [comment]
@silbinarywolf, if you're across the solution here, could you please put through a PR? I assume this will also require some testing/changes on the CI side of things.

**Comment by silbinarywolf** [comment]
@nglasl It will require changes on the CI side, but this wont break anything if our CI continues to use the `composer_dist` flag instead of `ni_build`

**Comment by silbinarywolf** [comment]
PR incoming.

**Comment by silbinarywolf** [comment]
@nglasl See PR above.

**Comment by nglasl** [comment]
The PR above has been merged, so closing this issue. Thanks :+1:
