### ISSUE TITLE
Update ~4.0 branch / tag to use SilverStripe 3.6

### ISSUE THREAD

**Issue by silbinarywolf** [symbiote/silverstripe-base#22]
Currently the default installed version is SS 3.5

**Comment by nglasl** [comment]
This is currently set to `~3.5@stable` which will resolve to the latest stable version `<4.0`. So, it should be retrieving the latest 3.7.X stable release (or 3.6.X at the time of this issue being opened). @silbinarywolf, can you please confirm your expectations here?

**Comment by silbinarywolf** [comment]
@nglasl I honestly can't remember. I'm guessing either:

- It ended up pulling down SS 3.5 for some reason
or
- I just wanted our base to be more accurate as to what SS version we have installed.

**Comment by nglasl** [comment]
@silbinarywolf considering this should already be working and that it's technically a moving target (3.6 was the latest, now 3.7 is the latest), are you okay for this one to be closed? If you're keen to update it, I'm more than happy for you to make the change :)

**Comment by silbinarywolf** [comment]
@nglasl I see no reason to be pedantic about this. If it angers me in the future, I'll just do a PR rather than raise an issue!

Closing!
