### ISSUE TITLE
SQLite3 not production ready with SilverStripe4

### ISSUE THREAD

**Issue by stephenmcm** [symbiote/silverstripe-base#23]
Sqlite3 module issue: [Polymorphic database fields are bad news for reconstruction](https://github.com/silverstripe/silverstripe-sqlite3/issues/45)

We should remove this module from base until it is updated to solve issue 45. The error is subtle and extremely hard to debug, which makes it a developer time sink.

**Comment by silbinarywolf** [comment]
@stephenmcm Happy to close this one off? :)

**Comment by stephenmcm** [comment]
Resolved in #24
