### ISSUE TITLE
Update project.yml for SilverStripe 4.1

### ISSUE THREAD

**Issue by silbinarywolf** [symbiote/silverstripe-base#26]
**The problem**
- `SilverStripe\View\SSViewer::theme` is deprecated. It's a bit confusing figuring out how to use the non-deprecated form. An example exists below. (ie. `themes`)
- SS4 defaults for MySQL aren't using our in-house standard.

**The solution**
```
SilverStripe\Core\Manifest\ModuleManifest:
  project: mysite
SilverStripe\View\SSViewer:
  themes:
    - simple
    - '$default'
  theme_enabled: true
Symbiote\Multisites\Model\Site:
  available_themes:
    - simple
---
Name: mysite-db
---
SilverStripe\ORM\Connect\MySQLDatabase:
  connection_charset: utf8mb4
  connection_collation: utf8mb4_unicode_ci
  charset: utf8mb4
  collation: utf8mb4_unicode_ci
```

**Comment by nglasl** [comment]
@silbinarywolf if you're across the solution, could you please put a PR through?

**Comment by silbinarywolf** [comment]
@nglasl I'll see if I can put this through sometime this month!

**Comment by silbinarywolf** [comment]
@nglasl PR link above.

**Comment by nglasl** [comment]
Thanks for putting that through in a PR, have merged :+1:
